ref(RiceNix): dropping nix-env dependencies

diff --git a/wslfiles/.local/bin/RiceNix b/wslfiles/.local/bin/RiceNix
--- a/wslfiles/.local/bin/RiceNix
+++ b/wslfiles/.local/bin/RiceNix
@@ -48,15 +48,16 @@
 #     su - "drksl" bash -c "export XDG_RUNTIME_DIR=/run/user/1000 && script -qI /dev/null"
 #     '
 
-#================================= Post-Install: ubuntu-nix arch-nix =================================#
+#================================= Post-Install: Run it inside tmux may restart gdm/lighdm =================================#
 
 # exit on error:
 set -eu
 
 # Detect non-root user:
 [ "$(id -u)" == 0 ]      && printf "\e[1;31m Run it as non-root user, nix-env doesn't suport root \e[0m\n" && exit 1
-( which sudo >/dev/nul ) && printf "\e[1;31m Install sudo, pacman/apt needs it                    \e[0m\n" && exit 1
+( which sudo >/dev/null ) || ( printf "\e[1;31m Install sudo, pacman/apt needs it                    \e[0m\n" && exit 1 )
 export SUDO="sudo"
+export DEBIAN_FRONTEND=noninteractive
 
 #-------------------------------------------- Dependencies -------------------------------------------#
 
@@ -72,26 +73,33 @@ export SUDO="sudo"
   $SUDO curl -L https://github.com/Jguer/yay/releases/download/v12.1.2/yay_12.1.2_x86_64.tar.gz | $SUDO tar -xzf- --strip-components=1 --directory="/usr/local/bin" "yay_12.1.2_x86_64/yay"
   $SUDO curl -L https://github.com/neovim/neovim/releases/download/v0.9.1/nvim.appimage                                     --create-dirs --output "/usr/local/bin/nvim"    && $SUDO chmod +x /usr/local/bin/nvim
 
-  # [ ! -e /.dockerenv ] && $SUDO pacman -S --noconfirm cronie festival-us fakeroot python-gobject xf86-input-synaptics # ArchWSL uses fakeroot-tcp
+  # [ ! -e /.dockerenv ] && $SUDO pacman -S --noconfirm festival-us fakeroot python-gobject # ArchWSL uses fakeroot-tcp
+  $SUDO pacman -S --noconfirm ghostscript imagemagick mpv pipewire-pulse poppler stow
+  git clone --depth=1                        https://github.com/zsh-users/zsh-autosuggestions                                "$HOME/.config/zsh-autosuggestions"
+  git clone --depth=1                        https://github.com/zdharma-continuum/fast-syntax-highlighting                   "$HOME/.config/fast-syntax-highlighting"
 }
 
 # Debian server/docker dependencies:
 [ -e /bin/apt ] && {
-  export DEBIAN_FRONTEND=noninteractive
-  $SUDO apt update
-  $SUDO apt install -y curl file git gcc libglib2.0-bin libsixel-bin locales make ripgrep sudo unzip xclip xz-utils zsh # ( libglib2.0-bin gio binary) (locales zsh-autosuggestions dep)
+  $SUDO apt update --fix-missing
+  $SUDO eatmydata apt install --no-install-recommends -y curl file git gcc libsixel-bin locales make ripgrep sudo unzip xclip xz-utils zsh # ( libglib2.0-bin gio binary breaks dependencies) (locales zsh-autosuggestions dep)
   $SUDO curl -L https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-gnu.tar.gz    | $SUDO tar -xzf- --directory="/tmp"  && $SUDO cp "/tmp/bat-v0.23.0-x86_64-unknown-linux-gnu/bat" "/usr/local/bin"
   $SUDO curl -L https://github.com/starship/starship/releases/download/v1.16.0/starship-x86_64-unknown-linux-gnu.tar.gz | $SUDO tar -xzf- --directory="/usr/local/bin/"
   $SUDO curl -L https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_x86_64.tar.gz   | $SUDO tar -xzf- --directory="/usr/local/bin/"
-  $SUDO curl -L https://github.com/gokcehan/lf/releases/download/r30/lf-linux-amd64.tar.gz                              | $SUDO tar -xzf- --directory="/usr/local/bin/"
+  $SUDO curl -L https://github.com/gokcehan/lf/releases/download/r31/lf-linux-amd64.tar.gz                              | $SUDO tar -xzf- --directory="/usr/local/bin/"
   $SUDO curl -L https://github.com/junegunn/fzf/releases/download/0.42.0/fzf-0.42.0-linux_amd64.tar.gz                  | $SUDO tar -xzf- --directory="/usr/local/bin/"
   $SUDO curl -L https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh                                     --create-dirs --output "/usr/share/fzf/completion.zsh"
   $SUDO curl -L https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh                                   --create-dirs --output "/usr/share/fzf/key-bindings.zsh"
   $SUDO curl -L https://github.com/antontkv/tmux-appimage/releases/download/3.3a/tmux-3.3a-x86_64.appimage                     --create-dirs --output "/usr/local/bin/tmux" && $SUDO chmod +x /usr/local/bin/tmux
+  $SUDO curl -L https://github.com/ImageMagick/ImageMagick/releases/download/7.1.1-18/ImageMagick--gcc-x86_64.AppImage         --create-dirs --output "/usr/local/bin/magick" && $SUDO chmod +x /usr/local/bin/magick
+  $SUDO curl -L https://github.com/ImageMagick/ImageMagick/releases/download/7.1.1-18/ImageMagick--gcc-x86_64.AppImage         --create-dirs --output "/usr/local/bin/convert" && $SUDO chmod +x /usr/local/bin/convert
   $SUDO chmod o+rx "/usr/share/fzf"
   $SUDO curl -L https://github.com/neovim/neovim/releases/download/v0.9.1/nvim.appimage                                     --create-dirs --output "/usr/local/bin/nvim"    && $SUDO chmod +x /usr/local/bin/nvim
 
-  # [ ! -e /.dockerenv ] && $SUDO apt install -y cron festvox-us-slt-hts python3-gi xserver-xorg-input-synaptics
+  # [ ! -e /.dockerenv ] && $SUDO apt install -y festvox-us-slt-hts python3-gi
+  $SUDO eatmydata apt --no-install-recommends -y install ghostscript mpv poppler-utils stow # imagemagick pipewire-pulse || ( $SUDO dpkg --configure -a; apt reinstall gdm3 lightdm )
+  git clone --depth=1                        https://github.com/zsh-users/zsh-autosuggestions                                "$HOME/.config/zsh-autosuggestions"
+  git clone --depth=1                        https://github.com/zdharma-continuum/fast-syntax-highlighting                   "$HOME/.config/fast-syntax-highlighting"
 }
 
 # locales for zsh-autosuggestions:
@@ -105,28 +113,38 @@ curl -L nixos.org/nix/install | sh && source "$HOME/.nix-profile/etc/profile.d/n
 # nix-env --install -E 'f: (import <nixpkgs> {}).mpv-unwrapped.override { sixelSupport = true; }'
 
 # GUI dependencies:
-[ ! -e /.dockerenv ] &&
-  $SUDO curl -L https://github.com/kovidgoyal/kitty/releases/download/v0.29.2/kitty-0.29.2-x86_64.txz | $SUDO tar -xJf- --directory="/usr/local" &&
-  $SUDO curl -L https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/WezTerm-20230712-072601-f4abf8fd-Ubuntu20.04.AppImage --create-dirs --output "/usr/local/bin/wezterm" && $SUDO chmod +x /usr/local/bin/wezterm &&
-  nix-env -iA \
-  dmenu \
-  devour \
-  light \
-  mpc_cli \
-  mpd \
-  ncmpcpp \
-  playerctl \
-  redshift \
-  sxhkd \
-  sxiv \
-  xcape \
-  xdo \
-  xdotool \
-  xdragon \
-  xorg.xmodmap \
-  xorg.xset \
-  zathura \
-  -f https://github.com/NixOS/nixpkgs/archive/f3841aa99b019e827633141317ee504a50c8c936.tar.gz # NixOS/nixpkgs/pull/253000/commits
+[ ! -e /.dockerenv ] && {
+
+  $SUDO curl -L https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/WezTerm-20230712-072601-f4abf8fd-Ubuntu20.04.AppImage --create-dirs --output "/usr/local/bin/wezterm" && $SUDO chmod +x /usr/local/bin/wezterm
+
+  # [ -e /bin/apt ] && $SUDO eatmydata apt --only-upgrade full-upgrade
+  # [ -e /bin/apt ] && $SUDO eatmydata apt install -y libgtk-3-dev # https://stackoverflow.com/questions/38752214/installing-libgtk-3-dev-unmet-dependencies
+  [ -e /bin/apt ] && $SUDO eatmydata apt --no-install-recommends -y install cron suckless-tools light playerctl redshift sxhkd sxiv xcape xdo xdotool x11-xserver-utils xserver-xorg-input-synaptics zathura-pdf-poppler; # mpc mpd ncmpcpp
+  [ -e /bin/pacman ] && $SUDO pacman -S --noconfirm cronie dmenu light playerctl redshift sxhkd sxiv xcape xdo xdotool xorg-xmodmap xorg-xset xf86-input-synaptics zathura-pdf-poppler; # mpc mpd ncmpcpp gtk3
+
+  # git clone https://github.com/mwh/dragon                    && cd dragon            && $SUDO make NAME=dragon-drop PREFIX=/usr/local install && cd .. && $SUDO rm -rf dragon # dragon-drop depends on gtk3
+  git clone https://github.com/donniebreve/touchcursor-linux && cd touchcursor-linux && $SUDO make && make install && cd .. && $SUDO rm -rf touchcursor-linux
+  git clone https://github.com/jrabinow/snapper-rollback.git && cd snapper-rollback  && $SUDO cp snapper-rollback.py /usr/local/sbin/snapper-rollback && $SUDO cp snapper-rollback.conf /etc && cd .. && $SUDO rm -rf snapper-rollback
+
+  # nix-env -iA \
+  # dmenu \     # suckless-tools
+  # devour \    # curl devour.sh
+  # light \     # light
+  # mpc_cli \
+  # mpd \
+  # ncmpcpp \
+  # playerctl \
+  # redshift \
+  # sxhkd \
+  # sxiv \
+  # xcape \
+  # xdo \
+  # xdotool \
+  # xdragon \      # git clone and make
+  # xorg.xmodmap \ #x11-xserver-utils
+  # xorg.xset \    #x11-xserver-utils
+  # zathura \
+  # -f https://github.com/NixOS/nixpkgs/archive/f3841aa99b019e827633141317ee504a50c8c936.tar.gz # NixOS/nixpkgs/pull/253000/commits
   # btrfs-progs \
   # bspwm \
   # cron \
@@ -151,20 +169,22 @@ curl -L nixos.org/nix/install | sh && source "$HOME/.nix-profile/etc/profile.d/n
   # snapper \
   # unclutter \
   # xorg.xorgserver \
-  # xorg.xinit \
+  # xorg.xinit
+
+}
 
 # Non GUI dependencies:
-nix-env -iA \
-  ffmpeg \
-  ghostscript \
-  imagemagick \
-  mpv \
-  pipewire \
-  poppler \
-  stow \
-  zsh-autosuggestions \
-  zsh-fast-syntax-highlighting \
-  -f https://github.com/NixOS/nixpkgs/archive/f3841aa99b019e827633141317ee504a50c8c936.tar.gz # NixOS/nixpkgs/pull/253000/commits
+  # nix-env -iA \
+  # ffmpeg \
+  # ghostscript \
+  # imagemagick \
+  # mpv \
+  # pipewire \
+  # poppler \
+  # stow \
+  # zsh-autosuggestions \
+  # zsh-fast-syntax-highlighting \
+  # -f https://github.com/NixOS/nixpkgs/archive/f3841aa99b019e827633141317ee504a50c8c936.tar.gz # NixOS/nixpkgs/pull/253000/commits
   # bat \
   # cht-sh \
   # fzf \
@@ -203,51 +223,51 @@ install_fonts() {
   git sparse-checkout add patched-fonts/3270
   git sparse-checkout add patched-fonts/CascadiaCode
   git sparse-checkout add patched-fonts/FiraCode
-  git sparse-checkout add patched-fonts/Terminus
+  # git sparse-checkout add patched-fonts/Terminus
   cp -r patched-fonts/3270         "$HOME"/.local/share/fonts
   cp -r patched-fonts/CascadiaCode "$HOME"/.local/share/fonts
   cp -r patched-fonts/FiraCode     "$HOME"/.local/share/fonts
-  cp -r patched-fonts/Terminus     "$HOME"/.local/share/fonts
+  # cp -r patched-fonts/Terminus     "$HOME"/.local/share/fonts
 
   # Font-Awesome:
   git clone --depth=1 --filter=blob:none --sparse https://github.com/FortAwesome/Font-Awesome /tmp/Font-Awesome
   cd /tmp/Font-Awesome
   git sparse-checkout add otfs
   git sparse-checkout add webfonts
-  mkdir           "$HOME"/.local/share/fonts/Font-Awesome
+  mkdir -p        "$HOME"/.local/share/fonts/Font-Awesome
   cp -r otfs/     "$HOME"/.local/share/fonts/Font-Awesome
   cp -r webfonts/ "$HOME"/.local/share/fonts/Font-Awesome
 
   # Noto Sans/Serif/Mono:
-  git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/notofonts.github.io /tmp/notofonts.github.io
-  cd /tmp/notofonts.github.io
-  git sparse-checkout add fonts/NotoSans/googlefonts
-  git sparse-checkout add fonts/NotoSansMono/googlefonts
-  git sparse-checkout add fonts/NotoSerif/googlefonts
-  mkdir                                "$HOME"/.local/share/fonts/NotoSans
-  mkdir                                "$HOME"/.local/share/fonts/NotoSansMono
-  mkdir                                "$HOME"/.local/share/fonts/NotoSerif
-  cp -r fonts/NotoSans/googlefonts     "$HOME"/.local/share/fonts/NotoSans
-  cp -r fonts/NotoSansMono/googlefonts "$HOME"/.local/share/fonts/NotoSansMono
-  cp -r fonts/NotoSerif/googlefonts    "$HOME"/.local/share/fonts/NotoSerif
+  # git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/notofonts.github.io /tmp/notofonts.github.io
+  # cd /tmp/notofonts.github.io
+  # git sparse-checkout add fonts/NotoSans/googlefonts
+  # git sparse-checkout add fonts/NotoSansMono/googlefonts
+  # git sparse-checkout add fonts/NotoSerif/googlefonts
+  # mkdir -p                             "$HOME"/.local/share/fonts/NotoSans
+  # mkdir -p                             "$HOME"/.local/share/fonts/NotoSansMono
+  # mkdir -p                             "$HOME"/.local/share/fonts/NotoSerif
+  # cp -r fonts/NotoSans/googlefonts     "$HOME"/.local/share/fonts/NotoSans
+  # cp -r fonts/NotoSansMono/googlefonts "$HOME"/.local/share/fonts/NotoSansMono
+  # cp -r fonts/NotoSerif/googlefonts    "$HOME"/.local/share/fonts/NotoSerif
 
   # Noto CJK:
-  git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/noto-cjk /tmp/noto-cjk
-  cd /tmp/noto-cjk
-  git sparse-checkout add google-fonts
-  mkdir              "$HOME"/.local/share/fonts/NotoCJK
-  cp -r google-fonts "$HOME"/.local/share/fonts/NotoCJK
+  # git clone --depth=1 --filter=blob:none --sparse https://github.com/notofonts/noto-cjk /tmp/noto-cjk
+  # cd /tmp/noto-cjk
+  # git sparse-checkout add google-fonts
+  # mkdir -p           "$HOME"/.local/share/fonts/NotoCJK
+  # cp -r google-fonts "$HOME"/.local/share/fonts/NotoCJK
 
   # Noto Color-Emoji:
   git clone --depth=1 --filter=blob:none --sparse https://github.com/googlefonts/noto-emoji /tmp/noto-emoji
   cd /tmp/noto-emoji
   git sparse-checkout add fonts
-  mkdir                       "$HOME"/.local/share/fonts/Noto-Emoji
+  mkdir -p                    "$HOME"/.local/share/fonts/Noto-Emoji
   cp fonts/NotoColorEmoji.ttf "$HOME"/.local/share/fonts/Noto-Emoji
 
   # Bedstead Font:
-  curl -L https://bjh21.me.uk/bedstead/bedstead-002.004.zip --output /tmp/bedstead-002.004.zip
-  unzip /tmp/bedstead-002.004.zip -d "$HOME"/.local/share/fonts
+  # curl -L https://bjh21.me.uk/bedstead/bedstead-002.004.zip --output /tmp/bedstead-002.004.zip
+  # unzip /tmp/bedstead-002.004.zip -d "$HOME"/.local/share/fonts
 
   # rofi emoji:
   # pip install --user --upgrade git+https://github.com/fdw/rofimoji@6.0.0
@@ -322,6 +342,8 @@ install_configs () {
   $SUDO mkdir -p /etc/X11/xorg.conf.d && $SUDO cp "$HOME"/.config/shell/10-synaptics.conf /etc/X11/xorg.conf.d
   command -v crontab                  && $SUDO crontab "$HOME"/.local/bin/cron/lowbatnotificationcron
   nix-collect-garbage -d
+  [ -e /bin/apt ] && $SUDO apt autoremove -y
+  [ -e /bin/pacman ] && yes | $SUDO pacman -Scc
 
   # Login shell:
   [ "$(id -u)" == 0 ] && export USER="root"
@@ -346,12 +368,12 @@ install_configs () {
 
 #------------------------------------------------ main -----------------------------------------------#
 
-install_dotfiles                              || ( echo $(tput -T ansi setaf 1) install_dotfiles failed    && exit 1; )
-[ ! -e /.dockerenv ] && ( install_fonts       || ( echo $(tput -T ansi setaf 1) install_fonts failed       && exit 1; ))
-[ ! -e /.dockerenv ] && ( install_touchcursor || ( echo $(tput -T ansi setaf 1) install_touchcursor failed && exit 1; ))
-# install_tmuxsixel                           || ( echo $(tput -T ansi setaf 1) install_tmuxsixel failed   && exit 1; )
-# install_xsixel                              || ( echo $(tput -T ansi setaf 1) install_xsixel failed      && exit 1; )
-install_configs                               || ( echo $(tput -T ansi setaf 1) install_configs failed     && exit 1; )
+install_dotfiles                                || ( echo $(tput -T ansi setaf 1) install_dotfiles failed    && exit 1; )
+[ ! -e /.dockerenv ] && ( install_fonts         || ( echo $(tput -T ansi setaf 1) install_fonts failed       && exit 1; ))
+# [ ! -e /.dockerenv ] && ( install_touchcursor || ( echo $(tput -T ansi setaf 1) install_touchcursor failed && exit 1; ))
+# install_tmuxsixel                             || ( echo $(tput -T ansi setaf 1) install_tmuxsixel failed   && exit 1; )
+# install_xsixel                                || ( echo $(tput -T ansi setaf 1) install_xsixel failed      && exit 1; )
+install_configs                                 || ( echo $(tput -T ansi setaf 1) install_configs failed     && exit 1; )
 
 printf "\e[1;32m ln -sf ~/.config/shell/.xprofile ~/.xsessionrc #if lightDM (xfce) \e[0m\n"
 printf "\e[1;32m Done! \e[0m\n"
